## port 설정 
server.port=80

## JSP 경로 설정 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

## Mybatis 설정
spring.datasource.hikari.username=user01
spring.datasource.hikari.password=user01
spring.datasource.url=jdbc:mariadb://15.164.250.162:3306/user01
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true

#단, 같은 클래스명이 존재하면 error   
mybatis.type-aliases-package=com.winter.app

logging.level.root=info

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB

app.upload.base=D:/GDJ94/upload/
app.upload=file:///GDJ94/upload/
app.upload.notice=D:/GDJ94/upload/notice/
app.upload.qna=D:/GDJ94/upload/qna/
app.upload.user=D:/GDJ94/upload/user/

app.upload.url=/files/**

category.board.notice=notice
category.board.qna=qna
category.user=user


spring.aop.proxy-target-class=true
spring.messages.basename=messages/message
spring.messages.encoding=UTF-8
spring.messages.always-use-message-format=true
## true: 예외를 발생시키지 않고 Key를 출력
## false: 예외를 발생
spring.messages.cache-duration=600