## port 설정 
server.port=80

## JSP 경로 설정 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

## Mybatis 설정
spring.datasource.hikari.username=user01
spring.datasource.hikari.password=user01
spring.datasource.url=jdbc:mariadb://15.164.250.162:3306/user01
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true

#단, 같은 클래스명이 존재하면 error   
mybatis.type-aliases-package=com.winter.app

logging.level.root=info

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

app.upload.base=D:/GDJ94/upload/
app.upload=file:///GDJ94/upload/
app.upload.notice=D:/GDJ94/upload/notice/
app.upload.qna=D:/GDJ94/upload/qna/
app.upload.user=D:/GDJ94/upload/user/

app.upload.url=/files/**

category.board.notice=notice
category.board.qna=qna
category.user=users
category.board.users=users

spring.aop.proxy-target-class=true
spring.messages.basename=messages/message
spring.messages.encoding=UTF-8
spring.messages.always-use-message-format=true
## true: 예외를 발생시키지 않고 Key를 출력
## false: 예외를 발생
spring.messages.cache-duration=600


spring.security.oauth2.registertion.kakao.client-id=938f5db0727157f1e233e29620003b17
spring.security.oauth2.registertion.kakao.client-secret=aa383aa2f3263f55ec2d13b317ec9a14
spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost/login/oauth2/code/kakao




#고정값 
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
# 회원가입시 가져오는 유저 정보 항목
spring.security.oauth2.client.registration.kakao.scope=   profile_nickname,profile_image
#업체명
spring.security.oauth2.client.registration.kakao.client-name=kakao
#인증 요청시 메서드 형식
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post

## Provider
#인가코드 요청 URI
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id











